export const resumeData = {
  name: "Andy Pumbien",
  title: "Senior Fullstack Software Developer",
  email: "apumbien@gmail.com",
  phone: "(403) 399-9289",
  location: "Courtenay, BC",
  linkedIn: "https://www.linkedin.com/in/andy-pumbien",
  summary:
    "Collaborative, proactive, and a seasoned Full-Stack Software Developer, I bring more than 13 years of experience in designing, building, and maintaining world-class applications tailored to client needs.",
  summary2:
    "I am recognized for my robust problem-solving skills, adaptability, and unwavering commitment to delivering the code of the highest standard.",
  techSkills: [
    {
      grouping: "lang",
      label: "Language",
      skills: [
        { name: "Java", companies: ["p2", "atb", "han"] },
        { name: "JavaScript", companies: ["p2", "atb", "han"] },
        { name: "TypeScript", companies: ["han"] },
        { name: "Kotlin", companies: ["atb"] },
        { name: "Python", companies: ["atb"] },
        { name: "C#", companies: ["p2"] },
        { name: "SQL", companies: ["p2", "atb", "han"] },
        { name: "NoSQL", companies: ["atb"] },
        { name: "GraphQL", companies: ["atb"] },
      ],
    },
    {
      grouping: "framework",
      label: "Frameworks",
      skills: [
        { name: "React", companies: ["atb", "han"] },
        { name: "Android", companies: ["atb"] },
        { name: "Express", companies: ["atb"] },
        { name: "Springboot", companies: ["atb"] },
      ],
    },
    {
      grouping: "runtime",
      label: "Runtime Environments",
      skills: [{ name: "NodeJS", companies: ["atb", "han"] }],
    },
    {
      grouping: "testing",
      label: "Testing",
      skills: [
        { name: "Test Automation", companies: ["atb", "han"] },
        { name: "Playwright", companies: ["han"] },
        { name: "Selenium", companies: ["atb"] },
        { name: "pytest", companies: ["atb"] },
      ],
    },
    {
      grouping: "db",
      label: "Data Bases",
      skills: [
        { name: "MySQL", companies: ["han"] },
        { name: "Postgres", companies: ["atb"] },
        { name: "Oracle", companies: ["p2"] },
        { name: "MongoDb", companies: ["atb"] },
      ],
    },
    {
      grouping: "cloud",
      label: "Cloud Services",
      skills: [
        { name: "AWS", companies: ["atb", "han"] },
        { name: "GCP", companies: ["atb"] },
        { name: "Firebase", companies: ["atb"] },
      ],
    },
    {
      grouping: "devops",
      label: "Dev Ops",
      skills: [
        { name: "Kubernetes", companies: ["atb"] },
        { name: "Terraform", companies: ["han"] },
        { name: "Octopus Deploy", companies: ["han"] },
        { name: "Jenkins", companies: ["p2"] },
      ],
    },
    {
      grouping: "source",
      label: "Source Control",
      skills: [
        { name: "GitHub", companies: ["han"] },
        { name: "Git", companies: ["atb", "han"] },
        { name: "GitLab", companies: ["atb"] },
        { name: "Team Foundation Server", companies: ["p2"] },
        { name: "SVN", companies: ["p2"] },
      ],
    },
    {
      grouping: "os",
      label: "Operating Systems",
      skills: [
        { name: "Windows", companies: ["atb", "han"] },
        { name: "Linux", companies: ["p2", "atb", "han"] },
        { name: "Mac OS", companies: ["p2", "atb", "han"] },
      ],
    },
    {
      grouping: "ide",
      label: "IDE's",
      skills: [
        { name: "VS Code", companies: ["atb", "han"] },
        { name: "IntelliJ", companies: ["han"] },
        { name: "Eclipse", companies: ["p2", "han"] },
        { name: "Visual Studio", companies: ["p2"] },
        { name: "Android Studio", companies: ["atb", "han"] },
        { name: "PyCharm", companies: ["atb"] },
      ],
    },
    {
      grouping: "other",
      label: "Other",
      skills: [
        { name: "Copilot", companies: ["han"] },
        { name: "Jira / Confluence", companies: ["atb", "han"] },
        { name: "Docusign", companies: ["atb"] },
        { name: "Box", companies: ["atb"] },
        { name: "Splunk", companies: ["atb"] },
        { name: "Sonar Cloud", companies: ["atb"] },
        { name: "Redux", companies: ["atb", "han"] },
        { name: "Microservices", companies: ["atb"] },
        { name: "RESTful APIs", companies: ["atb", "han"] },
      ],
    },
  ],
  professionalSkills: [
    "Mentorship",
    "Collaboration",
    "Productivity",
    "Problem-solving",
    "Communication",
    "Adaptability",
    "Time Management",
    "Leadership",
    "Cheerful Demeanor",
  ],
  professionalExperience: [
    {
      company: "Transact (formerly Hangry)",
      id: "han",
      period: "08/2021 – 07/2024",
      title: "Senior Full Stack Software Developer",
      duties: [
        "Designed, implemented, and tested new features for Transact food ordering applications (dashboard and web ordering app), including frontend (React) and backend (Java) development.",
        "Advocated for implementing test pyramid methodology and led efforts to implement E2E test automation utilizing MS Playwright, resulting in migration of +45% of test cases from manual to automated tests.",
        "Mentored new and existing team members on Transacts best practices for both React/Java applications.",
        "Actively participated in agile/scrum ceremonies and helped challenge the status quo.",
        "Developed a SaaS admin dashboard in React that is used to manage 500K mobile app users and 15m annual transactions.",
        "Developed a web React version of the mobile ordering application by reviewing the Android app to replicate the functionality.",
        "Developed and integrated Amazon - Just Walk Out technology, encompassing frontend (React), backend (Java), and AWS components.",
        "Spearheaded a Proof of Concept for transitioning our web applications from Create React App to Next.js, demonstrating potential performance improvements and streamlined development processes",
        "Developed and delivered engaging training materials, including how-to guides, best practice documentation and presentations to help enhance team knowledge and drive process improvements.",
        "Advocated for and championed 10% time for “Freedom Fridays” - a day for personal learning and professional development.",
      ],
    },
    {
      company: "ATB Financial, Calgary",
      id: "atb",
      period: "02/2018 – 08/2021",
      title: "Senior Full Stack Software Developer",
      duties: [
        "Key contributor responsible for designing, developing, and testing new features for ATB’s updated Android app.",
        "Leveraged Node.js and Express to design, build, and deploy numerous new microservices, creating a robust and scalable API layer.",
        "Ensured code quality by writing and maintaining automated API tests (pytest) and UI tests (Selenium).",
        "Led a POC and large-scale implementation of a solution to generate PDFs using Node.js for multiple projects.",
        "Experience with maintaining CICD pipelines, performing + monitoring multiple microservice deployments, and resolving security vulnerabilities.",
        "Active participant in agile ceremonies and PI planning.",
        "Collaborated with many stakeholders including architecture, QA, product, business, and leadership to ensure effective delivery.",
      ],
    },

    {
      company: "P2 Energy Solutions, Calgary",
      id: "p2",
      period: "06/2011 – 02/2018",
      title: "Software Developer",
      duties: [
        "Designed and developed new features for various P2 SaaS product offerings.",
        "Provided operational support by efficiently debugging, diagnosing, and fixing production bugs.",
        "Created detailed technical specification documents to aid in knowledge transfer and support.",
        "Team Lead position attained within the first year at P2 (during the time on Optix).",
        "Training/mentoring new team members on the use of the differing technologies used on different products.",
        "Liaising between BA’s, QAs, and the development team.",
        "Attended career fairs and delivered presentations to graduating students looking to start their careers in software development.",
      ],
    },
  ],
  education: [
    {
      school: "SAIT Polytechnic",
      course: "Object-Oriented Software Development",
    },
    {
      school: "ICSLearn.co.uk",
      course: "Web Design Diploma",
    },
    {
      school: "Sports Studies, University of Derby",
      course: "Bachelor of Arts (Honors)",
    },
  ],
  awards: [
    "ATB Quarterly Award for Excellence",
    "P2 Energy Solutions Employee Recognition",
  ],
  links: [{ url: "https://github.com/Pum8i", label: "GitHub" }],
  sideOptions: {
    description:
      "A simple implementation of my resume to help demostrate some of my React skills.",
  },
};
